# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb92373be6b17c091a2efcd988536e082ffde0f979c3b2c76a6f6edb79f2e5d47d804c559efc411843a8647e8f8f84b4ec1eca2b0614d0f1ec6a361baf325d3

test:
  secret_key_base: 1026c74642faf08a4dda594ab12f8c16492ad0e1874fdc61adbad96705d2191ab8f804bd8364f529e3cbbd59842b4f3ea95a09b218984ef5d0fbfd0006b2cfc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
